import type { RouteKey, SupportedLang } from "./routes";

type ToolMenuCopy = {
  utilityLabel: string;
  descriptions: Partial<Record<RouteKey, string>>;
};

export const toolMenuContent: Record<SupportedLang, ToolMenuCopy> = {
  es: {
    utilityLabel: "Utilidades",
    descriptions: {
      tiktokHashtags: "Hashtags para ganar alcance",
      tiktokCaptions: "Textos listos para publicar",
      tiktokIdeas: "Ideas rápidas para tus videos",
      tiktokHooks: "Ganchos que captan atención",
      instagramDownloader: "Descarga Reels y videos",
      instagramCaptionGenerator: "Captions para tus publicaciones",
      instagramHashtagGenerator: "Hashtags para más alcance",
      instagramBioGenerator: "Crea una bio atractiva",
      instagramReelsIdeas: "Ideas para nuevos Reels",
      youtubeTitleGenerator: "Títulos claros y atractivos",
      youtubeTagGenerator: "Etiquetas relevantes",
      youtubeHashtagGenerator: "Hashtags para tus videos",
      youtubeThumbnailDownloader: "Guarda miniaturas en calidad",
      socialMediaTextGenerator: "Textos para cualquier red",
      socialMediaCharacterCounter: "Mide límites por plataforma",
      shortVideoScriptGenerator: "Estructura videos cortos",
      shortVideoTitleHashtag: "Combina títulos y hashtags",
      wordCounter: "Cuenta palabras y caracteres",
      caseConverter: "Transforma mayúsculas y minúsculas",
      outlineGenerator: "Organiza trabajos y contenidos",
      assignmentTitleGenerator: "Genera títulos académicos",
    },
  },
  en: {
    utilityLabel: "Utilities",
    descriptions: {
      tiktokHashtags: "Hashtags to expand your reach",
      tiktokCaptions: "Ready-to-publish copy",
      tiktokIdeas: "Quick ideas for your videos",
      tiktokHooks: "Hooks that capture attention",
      instagramDownloader: "Download Reels and videos",
      instagramCaptionGenerator: "Captions for your posts",
      instagramHashtagGenerator: "Hashtags for more reach",
      instagramBioGenerator: "Create an engaging bio",
      instagramReelsIdeas: "Ideas for new Reels",
      youtubeTitleGenerator: "Clear, engaging titles",
      youtubeTagGenerator: "Relevant video tags",
      youtubeHashtagGenerator: "Hashtags for your videos",
      youtubeThumbnailDownloader: "Save high-quality thumbnails",
      socialMediaTextGenerator: "Copy for any social network",
      socialMediaCharacterCounter: "Check platform limits",
      shortVideoScriptGenerator: "Structure short videos",
      shortVideoTitleHashtag: "Combine titles and hashtags",
      wordCounter: "Count words and characters",
      caseConverter: "Change uppercase and lowercase",
      outlineGenerator: "Organize assignments and content",
      assignmentTitleGenerator: "Generate academic titles",
    },
  },
  pt: {
    utilityLabel: "Utilidades",
    descriptions: {
      tiktokHashtags: "Hashtags para ampliar o alcance",
      tiktokCaptions: "Textos prontos para publicar",
      tiktokIdeas: "Ideias rápidas para seus vídeos",
      tiktokHooks: "Ganchos que captam atenção",
      instagramDownloader: "Baixe Reels e vídeos",
      instagramCaptionGenerator: "Legendas para publicações",
      instagramHashtagGenerator: "Hashtags para mais alcance",
      instagramBioGenerator: "Crie uma bio atraente",
      instagramReelsIdeas: "Ideias para novos Reels",
      youtubeTitleGenerator: "Títulos claros e atraentes",
      youtubeTagGenerator: "Tags relevantes",
      youtubeHashtagGenerator: "Hashtags para seus vídeos",
      youtubeThumbnailDownloader: "Salve miniaturas em qualidade",
      socialMediaTextGenerator: "Textos para qualquer rede",
      socialMediaCharacterCounter: "Confira limites por plataforma",
      shortVideoScriptGenerator: "Estruture vídeos curtos",
      shortVideoTitleHashtag: "Combine títulos e hashtags",
      wordCounter: "Conte palavras e caracteres",
      caseConverter: "Altere maiúsculas e minúsculas",
      outlineGenerator: "Organize trabalhos e conteúdos",
      assignmentTitleGenerator: "Gere títulos acadêmicos",
    },
  },
};
